"""LLM adjudication layer (Phase 4).

An LLM is used as an adjudication layer over evidence generated by the
deterministic NLP components. It does not detect ambiguity on its own: it
judges candidates that the rule-based detectors proposed, using the rule-based
and semantic evidence gathered for each.
"""

from ambisense.llm.adjudicator import LLMAdjudicator
from ambisense.llm.errors import LLMError
from ambisense.llm.factory import build_adjudicator, build_provider
from ambisense.llm.providers.base import (
    ChatMessage,
    LLMProvider,
    LLMRequest,
    LLMResponse,
)

__all__ = [
    "LLMAdjudicator",
    "LLMError",
    "build_adjudicator",
    "build_provider",
    "ChatMessage",
    "LLMProvider",
    "LLMRequest",
    "LLMResponse",
]
